(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



BeginPackage["ExportRoutines`"];


iExportPath ["6240-53415-88351"]:="C:\\GooD\\Sync\\Microstocks\\FromMathematica\\"
iExportPath ["6239-99146-95515"]:="C:\\Shared\\Vector\\"
iExportPath ["6202-08025-54767"]:="C:\\export\\"
iExportPath::IDerror="Unknown machine ID";
iExportPath [___]:=(Message[iExportPath::IDerror];$Failed)

ExportPath[machineID_String]:=iExportPath[$MachineID]

ExportDateTime:=ToString@Row[Round/@DateList[],"-"]






ClearAll@resLength
resLength[results:{__}]:=Length[results]
resLength[___]:=0


picked={};
gradchkboxesValues=ConstantArray[False,resLength[results]];


(* ::Input::Initialization:: *)
ClearAll@displayResults
displayResults::inputError="Results have to be Graphics or Image";
displayResults[results:{__Graphics}|{__Image}]:=(gradchkboxesValues=ConstantArray[False,resLength[results]];
Multicolumn[MapThread[Column[{#1,#2},Alignment->Center]&,{results,Checkbox[Dynamic[gradchkboxesValues[[#]]]]&/@Range[Length@results]}],Spacings->{Automatic,1}]);
displayResults[""]:="";
displayResults[___]:=(Message[displayResults::inputError];"");

ClearAll@exportButton
exportButton[results:{__Graphics}|{__Image},filename_String]:=Button["\:042d\:043a\:0441\:043f\:043e\:0440\:0442\:0438\:0440\:043e\:0432\:0430\:0442\:044c \:0432\:044b\:0431\:0440\:0430\:043d\:043d\:044b\:0435",picked=Pick[results,gradchkboxesValues];
gradchkboxesValues=ConstantArray[False,resLength[results]];
MapThread[Export[ExportRoutines`ExportPath[$MachineID]<>filename<>"-"<>ExportRoutines`ExportDateTime<>"-0"<>ToString[#2]<>".eps",#1,"EPS"]&,{picked,Range[Length[picked]]}],ImageSize->770];
exportButton[___]:="";


EndPackage[];
